#!/bin/bash

SUCCESS=`cat hard_run$1 | grep Verified | wc -l`
FAIL=`cat hard_run$1 | grep "incorrect solver output" | wc -l`
TOTAL=`python -c "print $SUCCESS + $FAIL"`
python -c "print \"$SUCCESS/$TOTAL (\" + str(($SUCCESS / float($TOTAL))*100) \
+ \"%)\""
